
trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

name: $(BuildDefinitionName)_$(VersionNumber)_$(SourceBranchName)

variables:
  - name: BaseVersionNumber 
    value: "0.2"  
  - name: Minor 
    value: $[counter(variables['BaseVersionNumber'], 1)]
  - name: VersionNumber 
    value: $(BaseVersionNumber).$(Minor)
  
steps:
  - task: PowerShell@2
    displayName: "Update Build Number"
    inputs:
      targetType: 'inline'
      script: |
          $BuildName = $env:BUILD_DEFINITIONNAME +'_'+$env:VERSIONNUMBER +'_'+ $env:BUILD_SOURCEBRANCHNAME 
          Write-Host "##vso[build.updatebuildnumber]$BuildName"

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        sudo npm install -g vsce
        vsce package
        vsce publish $(VersionNumber) -p $(PAT)
      failOnStderr: true
      workingDirectory: $(System.DefaultWorkingDirectory)

  - task: CopyFiles@2
    displayName: "Copy Files to: $(build.artifactstagingdirectory)"
    inputs:
      Contents: |
        **
      TargetFolder: "$(build.artifactstagingdirectory)"
  
  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: parisienne"
    inputs:
      ArtifactName: parisienne